### ISSUE TITLE
Unable to login - 400 error on https://my.moneydashboard.com/landing/login

### ISSUE THREAD

**Issue by m-roberts** [shutupflanders/moneydashboard#1]
`https://my.moneydashboard.com/landing/login` , used [here](https://github.com/shutupflanders/moneydashboard/blob/8fd2192642911e53fd94701d29db9f0ade947acf/moneydashboard/moneydashboard.py#L33) at time of writing (v1.0.9) does not appear to be valid.

Code:
```
from moneydashboard import MoneyDashboard
md = MoneyDashboard("my_email", "my_password")
md.login()
```

Error:
```
[HTTP Error]: Failed to login (400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/moneydashboard/moneydashboard.py", line 66, in login
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    md.login()
  File "/usr/local/lib/python3.7/site-packages/moneydashboard/moneydashboard.py", line 69, in login
    raise LoginFailedException
moneydashboard.moneydashboard.LoginFailedException
```

**Comment by shutupflanders** [comment]
Thanks for pointing this out @m-roberts 
The problem is in the example code I've given, you need to specify the parameters when creating the MoneyDashboard class:
`md = MoneyDashboard(email="my_email", password="my_password")`
I've tested locally, if you could confirm this works for you please?

I've also updated the readme instructions.
Cheers

**Comment by m-roberts** [comment]
Login is now working - thanks!

However, you still have `getBalances` when it is now `get_balances`, and also you need to parse the response as JSON to access its object properties the way that you do.

My code is as follows:
```
from moneydashboard import MoneyDashboard
import json

md = MoneyDashboard(email="my_email", password="my_password")
balances = json.loads(md.get_balances())
print('Net Balance: ', balances['net_balance'])
```

**Comment by shutupflanders** [comment]
Cheers, I've update the documentation.

**Comment by My-Name-Is-Adam** [comment]
I get the same? error as above but it appears I have declared the username and password like you've mentioned. 

```
C:\Users\adam_\moneydashboard>python start.py
[HTTP Error]: Failed to login (400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login)
Traceback (most recent call last):
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 79, in _login
    response.raise_for_status()
  File "C:\Users\adam_\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adam_\moneydashboard\start.py", line 6, in <module>
    balances = json.loads(md.get_balances())
                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 146, in get_balances
    accounts = self._get_accounts()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 98, in _get_accounts
    self._login()
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 82, in _login
    raise LoginFailedException
moneydashboard.moneydashboard.LoginFailedException
``` 

I changed the url to https://my.moneydashboard.com/landing/
but then get the following error:

```
C:\Users\adam_\moneydashboard>python start.py
Traceback (most recent call last):
  File "C:\Users\adam_\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adam_\moneydashboard\start.py", line 5, in <module>
    balances = json.loads(md.get_balances())
                          ^^^^^^^^^^^^^^^^^
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 146, in get_balances
    accounts = self._get_accounts()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 98, in _get_accounts
    self._login()
  File "C:\Users\adam_\moneydashboard\moneydashboard\moneydashboard.py", line 87, in _login
    response_data = response.json()
                    ^^^^^^^^^^^^^^^
  File "C:\Users\adam_\AppData\Roaming\Python\Python311\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 3 column 1 (char 4)
``` 

Code in start.py I am using is:
```
from moneydashboard import MoneyDashboard
import moneydashboard
import json
md = MoneyDashboard(email="EMAIL", password="MYPASS")
balances = json.loads(md.get_balances())
print('Net Balance: ', balances['net_balance'])
```
